# Basic stochastic processes between shapes described as simple functions in $L^2(\mathbb{S}^2, \mathbb{R}^3)$.

In [1]:
import sys
import numpy as np

sys.path.insert(0,"../")
from utils import shape_stochastics

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## Q-Wiener process on spherical harmonic basis applied to the sphere

In [2]:
theta, phi = shape_stochastics.make_grid(N=32) #Build a grid on the sphere with a given resolution given by N

### Shape defined through 3 separated functions giving the xyz coordinates ###
def sphere_function_x(theta, phi):
    return np.sin(theta)*np.cos(phi)

def sphere_function_y(theta, phi):
    return np.sin(theta)*np.sin(phi)

def sphere_function_z(theta, phi):
    return np.cos(theta)

n = 25 #choose a resolution for the sph decomposition (HAS TO BE A SQUARED NUMBER FOR ISOTROPIC NOISE !!!)
Q = np.eye(n)
Q = np.diag(np.array([1/((k+2)*(k+1)) for k in range (0,n)]))

In [15]:
sphere_function_x(theta,phi)

array([0.00000000e+00, 1.01168322e-01, 2.01298520e-01, ...,
       2.00298223e-01, 1.00665594e-01, 1.21856125e-16])

In [ ]:
### Compute the Q-Wiener process and output the list of meshes during the process and a .gif file 
shape_stochastics.compute_wiener_process(sphere_function_x, sphere_function_y, sphere_function_z,
                                         theta = theta, phi = phi, Q = Q, n = n, t=120, n_step=50, make_gif = True,
                                         file_dir = "tests/wiener_process_fshape", file_name = "Q_squared_225coeffs.gif")

array([[[ 8.56412533e-17,  1.01168322e-01,  2.01298520e-01, ...,
          2.00298223e-01,  1.00665594e-01,  6.37079957e-18],
        [ 1.46368130e-18, -7.05212640e-18, -2.64287051e-17, ...,
         -2.00428602e-02, -1.00731120e-02,  2.62851617e-18],
        [ 1.00000000e+00,  9.94869323e-01,  9.79529941e-01, ...,
         -9.79529941e-01, -9.94869323e-01, -1.00000000e+00]],

       [[ 6.26584899e-02,  1.64000666e-01,  2.63821561e-01, ...,
          2.31991128e-01,  1.33247200e-01,  3.37139222e-02],
        [-5.99639645e-02, -5.97978029e-02, -5.95886383e-02, ...,
         -6.73824136e-02, -5.55798436e-02, -4.37424843e-02],
        [ 9.55105047e-01,  9.48073014e-01,  9.31096324e-01, ...,
         -9.92768882e-01, -1.00835061e+00, -1.01383021e+00]],

       [[-3.66860561e-03,  9.70347481e-02,  1.96277609e-01, ...,
          1.73887717e-01,  7.37193180e-02, -2.70989858e-02],
        [-6.13245588e-02, -5.91759626e-02, -5.68638376e-02, ...,
         -5.38317685e-02, -4.26034421e-02, -3.165

## Q-brownian bridge process between 2 functional shapes

In [2]:
theta, phi = shape_stochastics.make_grid(N=32)
n = 25
lambdas = np.array([1/(np.sqrt(k+1)) for k in range (0,n)])
Q = np.diag(lambdas) #covariance operator
Q = np.eye(n)

def sphere_function_x_start(theta, phi):
    return np.sin(theta)*np.cos(phi)

def sphere_function_y_start(theta, phi):
    return np.sin(theta)*np.sin(phi)

def sphere_function_z_start(theta, phi):
    return np.cos(theta)

def sphere_function_x_end(theta, phi):
    return 2*np.sin(theta)*np.cos(phi)

def sphere_function_y_end(theta, phi):
    return 2*np.sin(theta)*np.sin(phi)

def sphere_function_z_end(theta, phi):
    return 2*np.cos(theta)

In [3]:
### Compute the Q-Wiener bridge process and output the list of meshes during the process and a .gif file 
shape_stochastics.compute_simplebridge(sphere_function_x_start, sphere_function_y_start, sphere_function_z_start,
                                         sphere_function_x_end, sphere_function_y_end, sphere_function_z_end,
                                         theta = theta, phi = phi, Q = Q, n = n)

array([[[ 1.07570722e-17,  1.01168327e-01,  2.01298529e-01, ...,
          2.00298232e-01,  1.00665598e-01, -1.42261643e-17],
        [ 3.62425013e-18, -5.14751437e-19, -4.07711949e-18, ...,
         -2.00428611e-02, -1.00731124e-02,  4.19052129e-18],
        [ 1.00000005e+00,  9.94869369e-01,  9.79529986e-01, ...,
         -9.79529986e-01, -9.94869369e-01, -1.00000005e+00]],

       [[-4.68399524e-02,  9.01370115e-02,  2.41077250e-01, ...,
          5.98031473e-01,  4.63007573e-01,  3.19157564e-01],
        [-7.64469559e-02, -7.07861187e-02, -6.07100393e-02, ...,
          2.30048047e-01,  2.23521854e-01,  1.89961490e-01],
        [ 1.03799973e+00,  9.87900622e-01,  9.22392571e-01, ...,
         -1.05049300e+00, -1.12929182e+00, -1.20104774e+00]],

       [[-1.16173436e-01,  9.38086280e-02,  3.01803771e-01, ...,
          7.20130685e-01,  6.54336287e-01,  5.71531436e-01],
        [-2.09698286e-01, -1.67227374e-01, -1.29197955e-01, ...,
          4.95913319e-03,  8.50934569e-02,  1.350

## Fractional spectral Wiener process in H²

In [25]:
theta, phi = shape_stochastics.make_grid(N=32) #Build a grid on the sphere with a given resolution given by N

### Shape defined through 3 separated functions giving the xyz coordinates ###
def sphere_function_x(theta, phi):
    return np.sin(theta)*np.cos(phi)

def sphere_function_y(theta, phi):
    return np.sin(theta)*np.sin(phi)

def sphere_function_z(theta, phi):
    return np.cos(theta)

n = 49 #choose a resolution for the sph decomposition (HAS TO BE A SQUARED NUMBER FOR ISOTROPIC NOISE !!!)
#Q = np.eye(n)
lambdas = np.array([1/np.sqrt(1 + (k+2)*(k+1)) for k in range (0,n)])
Q = np.diag(lambdas)
H = 0.8

In [26]:
### Compute the Q-Wiener process and output the list of meshes during the process and a .gif file 
### RUN TWICE
shape_stochastics.compute_fractional_process(sphere_function_x, sphere_function_y, sphere_function_z,
                                         theta = theta, phi = phi, Q = Q, H = H, n = n, t=1, n_step=50, make_gif = True,
                                         file_dir = "tests/fractional_process_fshape", file_name = "Q_Bessel_49_H0-8coeffs.gif")

array([[[-0.01157019,  0.08891386,  0.18916498, ...,  0.19565624,
          0.09600299, -0.00489842],
        [-0.00194447, -0.00136364, -0.00174598, ..., -0.03076983,
         -0.01945875, -0.00832936],
        [ 1.00551611,  1.00021957,  0.98571386, ..., -0.97274034,
         -0.98982928, -0.99553808]],

       [[-0.02446628,  0.07681729,  0.17817893, ...,  0.1991581 ,
          0.09817155, -0.00445013],
        [-0.01249118, -0.01285297, -0.01389625, ..., -0.03375577,
         -0.02048036, -0.00745286],
        [ 0.9880634 ,  0.98351583,  0.97052573, ..., -0.96378703,
         -0.98159799, -0.98764752]],

       [[-0.04376678,  0.05590322,  0.15660548, ...,  0.20551563,
          0.10498139,  0.00121283],
        [-0.01417161, -0.01383798, -0.01474358, ..., -0.03653842,
         -0.02346936, -0.00994363],
        [ 0.97689044,  0.9732451 ,  0.96180918, ..., -0.95550818,
         -0.9754243 , -0.98281392]],

       ...,

       [[-0.02487614,  0.02356416,  0.0722855 , ...,  0.4956431