# Basic stochastic processes between shapes described as simple functions in $L^2(\mathbb{S}^2, \mathbb{R}^3)$.

In [1]:
import sys
import numpy as np

sys.path.insert(0,"../")
from utils import shape_stochastics

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## Q-Wiener process on spherical harmonic basis applied to the sphere

In [2]:
theta, phi = shape_stochastics.make_grid(N=64) #Build a grid on the sphere with a given resolution given by N

### Shape defined through 3 separated functions giving the xyz coordinates ###
def sphere_function_x(theta, phi):
    return np.sin(theta)*np.cos(phi)

def sphere_function_y(theta, phi):
    return np.sin(theta)*np.sin(phi)

def sphere_function_z(theta, phi):
    return np.cos(theta)

n = 25 #choose a resolution for the sph decomposition (HAS TO BE A SQUARED NUMBER FOR ISOTROPIC NOISE !!!)
Q = np.eye(n)
#Q = np.diag(np.array([1/((k+2)*(k+1)) for k in range (0,n)]))

In [3]:
sphere_function_x(theta,phi)

array([0.00000000e+00, 4.98458857e-02, 9.95678466e-02, ...,
       9.94460170e-02, 4.97848950e-02, 1.22314834e-16])

In [4]:
### Compute the Q-Wiener process and output the list of meshes during the process and a .gif file 
shape_stochastics.compute_wiener_process(sphere_function_x, sphere_function_y, sphere_function_z,
                                         theta = theta, phi = phi, Q = Q, n = n, t=1, n_step=10, make_gif = True,
                                         file_dir = "tests/wiener_process", file_name = "test.gif")

array([[[ 1.07570697e-17,  4.98458857e-02,  9.95678466e-02, ...,
          9.94460170e-02,  4.97848950e-02, -1.42261677e-17],
        [ 3.62425138e-18,  1.39199870e-18, -4.58861234e-19, ...,
         -4.92400040e-03, -2.46506447e-03,  4.19052257e-18],
        [ 1.00000000e+00,  9.98756921e-01,  9.95030775e-01, ...,
         -9.95030775e-01, -9.98756921e-01, -1.00000000e+00]],

       [[ 7.55290432e-02,  1.23279509e-01,  1.70170003e-01, ...,
          5.76337169e-02,  9.51125408e-03, -3.91441888e-02],
        [-3.44543782e-02, -2.40404289e-02, -1.31129733e-02, ...,
          4.25506153e-02,  3.93215189e-02,  3.47324525e-02],
        [ 1.02214940e+00,  1.02308979e+00,  1.02066823e+00, ...,
         -1.06703940e+00, -1.07503076e+00, -1.07984717e+00]],

       [[ 9.96976519e-02,  1.40481264e-01,  1.79676948e-01, ...,
          3.65616168e-03, -5.20291325e-02, -1.08934562e-01],
        [-6.37582971e-02, -5.90225442e-02, -5.29195415e-02, ...,
          5.09752995e-02,  4.31808761e-02,  3.411

## Q-brownian bridge process between 2 functional shapes

In [2]:
theta, phi = shape_stochastics.make_grid(N=32)
n = 25
lambdas = np.array([1/(np.sqrt(k+1)) for k in range (0,n)])
Q = np.diag(lambdas) #covariance operator
Q = np.eye(n)

def sphere_function_x_start(theta, phi):
    return np.sin(theta)*np.cos(phi)

def sphere_function_y_start(theta, phi):
    return np.sin(theta)*np.sin(phi)

def sphere_function_z_start(theta, phi):
    return np.cos(theta)

def sphere_function_x_end(theta, phi):
    return 2*np.sin(theta)*np.cos(phi)

def sphere_function_y_end(theta, phi):
    return 2*np.sin(theta)*np.sin(phi)

def sphere_function_z_end(theta, phi):
    return 2*np.cos(theta)

In [3]:
### Compute the Q-Wiener bridge process and output the list of meshes during the process and a .gif file 
shape_stochastics.compute_simplebridge(sphere_function_x_start, sphere_function_y_start, sphere_function_z_start,
                                         sphere_function_x_end, sphere_function_y_end, sphere_function_z_end,
                                         theta = theta, phi = phi, Q = Q, n = n)

array([[[ 1.07570722e-17,  1.01168327e-01,  2.01298529e-01, ...,
          2.00298232e-01,  1.00665598e-01, -1.42261643e-17],
        [ 3.62425013e-18, -5.14751437e-19, -4.07711949e-18, ...,
         -2.00428611e-02, -1.00731124e-02,  4.19052129e-18],
        [ 1.00000005e+00,  9.94869369e-01,  9.79529986e-01, ...,
         -9.79529986e-01, -9.94869369e-01, -1.00000005e+00]],

       [[-4.68399524e-02,  9.01370115e-02,  2.41077250e-01, ...,
          5.98031473e-01,  4.63007573e-01,  3.19157564e-01],
        [-7.64469559e-02, -7.07861187e-02, -6.07100393e-02, ...,
          2.30048047e-01,  2.23521854e-01,  1.89961490e-01],
        [ 1.03799973e+00,  9.87900622e-01,  9.22392571e-01, ...,
         -1.05049300e+00, -1.12929182e+00, -1.20104774e+00]],

       [[-1.16173436e-01,  9.38086280e-02,  3.01803771e-01, ...,
          7.20130685e-01,  6.54336287e-01,  5.71531436e-01],
        [-2.09698286e-01, -1.67227374e-01, -1.29197955e-01, ...,
          4.95913319e-03,  8.50934569e-02,  1.350

## Fractional spectral Wiener process in H²

In [11]:
theta, phi = shape_stochastics.make_grid(N=64) #Build a grid on the sphere with a given resolution given by N

### Shape defined through 3 separated functions giving the xyz coordinates ###
def sphere_function_x(theta, phi):
    return np.sin(theta)*np.cos(phi)

def sphere_function_y(theta, phi):
    return np.sin(theta)*np.sin(phi)

def sphere_function_z(theta, phi):
    return np.cos(theta)

n = 49 #choose a resolution for the sph decomposition (HAS TO BE A SQUARED NUMBER FOR ISOTROPIC NOISE !!!)
#Q = np.eye(n)
lambdas = np.array([1/np.sqrt((k+2)*(k+1)) for k in range (0,n)])
Q = np.diag(lambdas)
H = 0.3

In [12]:
### Compute the Q-Wiener process and output the list of meshes during the process and a .gif file 
shape_stochastics.compute_fractional_process(sphere_function_x, sphere_function_y, sphere_function_z,
                                         theta = theta, phi = phi, Q = Q, H = H, n = n, t=1.2, n_step=50, make_gif = True,
                                         file_dir = "tests/fractional_process_fshape", file_name = "test.gif")

array([[[ 7.87564055e-02,  1.16987424e-01,  1.55600750e-01, ...,
          1.06330696e-01,  5.30669793e-02, -8.93868278e-04],
        [-2.05907582e-02, -1.85776021e-02, -1.68710860e-02, ...,
         -9.33046076e-02, -9.51546330e-02, -9.72117061e-02],
        [ 9.71414667e-01,  9.75990264e-01,  9.78917366e-01, ...,
         -9.51719308e-01, -9.58759518e-01, -9.63004456e-01]],

       [[ 8.38134376e-02,  1.21501153e-01,  1.58800704e-01, ...,
          9.72319814e-02,  4.49902572e-02, -7.20422577e-03],
        [ 1.38284688e-02,  2.07172503e-02,  2.59712636e-02, ...,
         -3.08180274e-02, -2.72788451e-02, -2.40754587e-02],
        [ 1.17386283e+00,  1.17499879e+00,  1.17331390e+00, ...,
         -9.46842133e-01, -9.49985898e-01, -9.50076221e-01]],

       [[ 1.34521626e-01,  1.70958084e-01,  2.06424671e-01, ...,
          7.01481989e-02,  1.39801689e-02, -4.26176962e-02],
        [-7.05105428e-02, -6.64471008e-02, -6.18666449e-02, ...,
         -8.47540148e-02, -8.39840217e-02, -8.317